added tests

diff --git a/transfer b/transfer
--- a/transfer
+++ b/transfer
@@ -1,7 +1,65 @@
 #!/usr/bin/env bash
 
-# write to output to tmpfile because of progress bar
-tmpfile=$( mktemp -t transferXXX )
-curl --progress-bar --upload-file $1 https://transfer.sh/$(basename $1) >> $tmpfile;
-cat $tmpfile;
-rm -f $tmpfile;
+programname=$0
+
+function usage {
+    echo "Usage: $programname target"
+    echo "    target - filename or directory to upload"
+    exit 1
+}
+
+transfer() {
+    # check arguments
+    if [ $# -eq 0 ];
+    then
+        echo "No arguments specified."
+        usage;
+        return 1
+    fi
+
+    # get temporarily filename, output is written to this file show progress can be showed
+    tmpfile=$( mktemp -t transferXXX )
+
+    # upload stdin or file
+    file=$1
+
+    if tty -s;
+    then
+        basefile=$(basename "$file" | sed -e 's/[^a-zA-Z0-9._-]/-/g')
+
+        if [ ! -e $file ];
+        then
+            echo "File $file doesn't exists."
+            return 1
+        fi
+
+        if [ -d $file ];
+        then
+            # zip directory and transfer
+            zipfile=$( mktemp -t transferXXX.zip )
+            cd $(dirname $file) && zip -r -q - $(basename $file) >> $zipfile
+            curl --progress-bar --upload-file "$zipfile" "https://transfer.sh/$basefile.zip" >> $tmpfile
+            rm -f $zipfile
+        else
+            # transfer file
+            curl --progress-bar --upload-file "$file" "https://transfer.sh/$basefile" >> $tmpfile
+        fi
+    else
+        # transfer pipe
+        curl --progress-bar --upload-file "-" "https://transfer.sh/$file" >> $tmpfile
+    fi
+
+    # cat output link
+    cat $tmpfile
+
+    # cleanup
+    rm -f $tmpfile
+}
+
+curl --version 2>&1 > /dev/null
+if [ $? -ne 0 ]; then
+    echo "Could not find curl."
+    exit 1
+fi
+
+transfer;
